create_clock -period 1 -name clk[0]  clk[0]
create_clock -period 1 -name clk[1]  clk[1]
create_clock -period 1 -name clk[2]  clk[2]
create_clock -period 1 -name clk[3]  clk[3]
create_clock -period 1 -name clk[4]  clk[4]
create_clock -period 1 -name clk[5]  clk[5]
create_clock -period 1 -name clk[6]  clk[6]
create_clock -period 1 -name clk[7]  clk[7]
create_clock -period 1 -name clk[8]  clk[8]
create_clock -period 1 -name clk[9]  clk[9]
create_clock -period 1 -name clk[10] clk[10]
create_clock -period 1 -name clk[11] clk[11]
create_clock -period 1 -name clk[12] clk[12]
create_clock -period 1 -name clk[13] clk[13]
create_clock -period 1 -name clk[14] clk[14]
create_clock -period 1 -name clk[15] clk[15]
derive_clock_uncertainty
set_false_path -from rst -to rst