package lynx.verilog;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Logger;

import lynx.data.Design;
import lynx.data.InterfacePort;
import lynx.xml.XMLIO;

public class VerilogOut {

    private static final Logger log = Logger.getLogger(XMLIO.class.getName());

    public static void writeVerilogDesign(Design design) throws FileNotFoundException, UnsupportedEncodingException {

        log.info("Writing out design to " + design.getName() + ".v");

        PrintWriter writer = new PrintWriter("designs/" + design.getName() + ".v", "UTF-8");

        writePreamble(design, writer);

        writeInterface(design, writer);

        writer.close();
    }

    private static void writeInterface(Design design, PrintWriter writer) {
        writer.println("module " + design.getName());
        writer.println("(");

        for (InterfacePort intPort : design.getInterfacePorts()) {
            String widthPart = intPort.getWidth() > 1 ? " [" + (intPort.getWidth() - 1) + ":" + "0] " : " ";
            writer.println("\t" + intPort.getDirection() + widthPart + intPort.getName() + ";");
        }

        writer.println(");");
        writer.println();
    }

    private static void writePreamble(Design design, PrintWriter writer) {
        writer.println("// auto-generated by noclynx");
        writer.println();
    }

}
